apiVersion: v1
kind: ReplicationController
metadata:
    name: go-ultimate-server
spec:
    replicas: 1
    selector:
        app: go-ultimate-server
    template:
        metadata:
            name: go-ultimate-server
            labels:
                app: go-ultimate-server
        spec:
            containers:

              - name: go-ultimate-server
                image: docker.io/sejvlond/go-ultimate-server
                #imagePullPolicy: Always
                ports:
                  - containerPort: 9876
