apiVersion: v1
kind: ReplicationController
metadata:
    name: tarsier
spec:
    replicas: 1
    selector:
        app: tarsier
    template:
        metadata:
            name: tarsier
            labels:
                app: tarsier
        spec:
            containers:

              - name: tarsier
                image: docker.dev/fulltext-frontend/tarsier
                #imagePullPolicy: Always
                ports:
                  - containerPort: 8888
                  - containerPort: 9999
                volumeMounts:
                  - name: tarsier-logs
                    mountPath: /www/tarsier/logs
                  - name: tarsier-tmp
                    mountPath: /www/tarsier/tmp
                  - name: tarsier-cert
                    mountPath: /www/tarsier/secrets
                    readOnly: true
                  - name: tarsier-conf
                    mountPath: /www/tarsier/conf
                    readOnly: true

              - name: kafkafeeder
                image: docker.dev/fulltext-frontend/kafkafeeder-beta
                #imagePullPolicy: Always
                ports:
                  - containerPort: 8796
                volumeMounts:
                  - name: kf-logs
                    mountPath: /www/kafkafeeder-beta/logs/
                  - name: kf-self-logs
                    mountPath: /www/kafkafeeder-beta/self-logs/
                  - name: kf-conf
                    mountPath: /www/kafkafeeder-beta/conf/
                    readOnly: true

              - name: cp-kafkafeeder
                image: docker.dev/ondrej.sejvl/cp-if-not-exists-and-sleep
                args:
                  - "/src/kafkafeeder.yaml"
                  - "/dst/kafkafeeder.yaml"
                  - "5000h"
                volumeMounts:
                  - name: tarsier-kafkafeeder
                    mountPath: /src/
                  - name: tarsier-logs
                    mountPath: /dst/

              - name: cp-kafkafeeder-kafkafeeder
                image: docker.dev/ondrej.sejvl/cp-if-not-exists-and-sleep
                args:
                  - "/src/kafkafeeder.yaml"
                  - "/dst/kafkafeeder.yaml"
                  - "5000h"
                volumeMounts:
                  - name: kf-kafkafeeder
                    mountPath: /src/
                  - name: kf-self-logs
                    mountPath: /dst/

            volumes:
              - name: tarsier-tmp
                glusterfs:
                    endpoints: glusterfs-cluster
                    path: /tarsier
              - name: tarsier-logs
                hostPath:
                    path: /www/logs/tarsier/
              - name: tarsier-cert
                secret:
                    secretName: tarsier-cert
              - name: tarsier-conf
                secret:
                    secretName: tarsier-conf
              - name: tarsier-kafkafeeder
                secret:
                    secretName: tarsier-kafkafeeder

              - name: kf-logs
                hostPath:
                    path: /www/logs/
              - name: kf-self-logs
                hostPath:
                    path: /www/logs/tarsier-kafkafeeder/
              - name: kf-conf
                secret:
                    secretName: tarsier-kafkafeeder-conf
              - name: kf-kafkafeeder
                secret:
                    secretName: tarsier-kafkafeeder-kafkafeeder

