apiVersion: v1
kind: ReplicationController
metadata:
    name: python-ultimate-server
spec:
    replicas: 1
    selector:
        app: python-ultimate-server
    template:
        metadata:
            name: python-ultimate-server
            labels:
                app: python-ultimate-server
        spec:
            containers:

              - name: python-ultimate-server
                image: docker.io/sejvlond/python-ultimate-server
                #imagePullPolicy: Always
                ports:
                  - containerPort: 6789

                volumeMounts:
                  - name: server-conf
                    mountPath: /www/ultimate-server/conf
                    readOnly: true

            volumes:
              - name: server-conf
                secret:
                    secretName: python-ultimate-server-conf
